
///parameters
#max_hybrids = 20000
#max_asymble = 10

///Molecules

//linkers
#l1 CCO                                            : # Ethoxy group
#l2 CC(=O)O                                        : # Isopropyl group
#l3 CC(=O)CC                                       :  # Butyl group
#l4 C1=CC=CC=C1                                    : # Benzene ring
#l5 C1CCCCC1                                      :   # Cyclohexane ring
#l6 C@@C                                           :   # Stereochemistry notation
#l7 C#C                                            : # Triple bond

//pharmacophores
#P1 CNC1=C2C=CC(Cl)=CC2=NC=C1                      :  # Specific heterocyclic structure
#P2 c1(ccc(cc1)S(=O)(N)=O)N                        :  # Another aromatic sulfonamide group3
#P3 S(=O)(c1ccc(N)cc1)(=O)N(C)C                    :  # Another sulfonamide group
#P4 CN(S(c1ccc(cc1)N)(=O)=O)C                      :  # Another functionalized amide
#P5 N1C2NCC(=NC2C(NC=1N)=O)C                       :  # Another heterocyclic structure
#P6 CN[C@H]1CC(O[C@@H]1COC)N1C=C(C)C(=O)NC1=O     :  # Complex structure
#P7 CCC1=NC(N)=NC(N)=C1C                           :  # Another complex structure
#P8 CN1CCNCC1                                      :  # A cyclic amine
#P9 [H][C@@]1(C)CN(C)CCN1                          :  # Stereochemical notation with amines
#P10 [H]N1CCC[C@]2([H])CN(C)C[C@]12[H]              :  # Another stereochemically complex structure
#P11 CN1CCCC[C@@H](N)C1                             :  # Another cyclic structure with nitrogen
  
        